apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-state
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: redis-master.demo.svc.cluster.local:6379
    - name: redisPassword
      secretKeyRef:
        name: redis
        key: redis-password
    - name: actorStateStore
      value: "true"
auth:
  secretStore: kubernetes
